package cn.yiueil.meeting.mapper;

import cn.yiueil.meeting.entity.MeetingRemindExample;
import cn.yiueil.meeting.entity.MeetingRemindKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MeetingRemindMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_remind
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    long countByExample(MeetingRemindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_remind
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    int deleteByExample(MeetingRemindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_remind
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    int deleteByPrimaryKey(MeetingRemindKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_remind
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    int insert(MeetingRemindKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_remind
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    int insertSelective(MeetingRemindKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_remind
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    List<MeetingRemindKey> selectByExample(MeetingRemindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_remind
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    int updateByExampleSelective(@Param("record") MeetingRemindKey record, @Param("example") MeetingRemindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_remind
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    int updateByExample(@Param("record") MeetingRemindKey record, @Param("example") MeetingRemindExample example);
}