package cn.yiueil.meeting.mapper;

import cn.yiueil.meeting.entity.MeetingUser;
import cn.yiueil.meeting.entity.MeetingUserExample;
import cn.yiueil.meeting.entity.MeetingUserKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MeetingUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_user
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    long countByExample(MeetingUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_user
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    int deleteByExample(MeetingUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_user
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    int deleteByPrimaryKey(MeetingUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_user
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    int insert(MeetingUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_user
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    int insertSelective(MeetingUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_user
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    List<MeetingUser> selectByExample(MeetingUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_user
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    MeetingUser selectByPrimaryKey(MeetingUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_user
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    int updateByExampleSelective(@Param("record") MeetingUser record, @Param("example") MeetingUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_user
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    int updateByExample(@Param("record") MeetingUser record, @Param("example") MeetingUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_user
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    int updateByPrimaryKeySelective(MeetingUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_user
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    int updateByPrimaryKey(MeetingUser record);
}