package cn.yiueil.meeting.mapper;

import cn.yiueil.meeting.entity.MeetingAnnex;
import cn.yiueil.meeting.entity.MeetingAnnexExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MeetingAnnexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_annex
     *
     * @mbg.generated Sun Mar 15 12:53:12 CST 2020
     */
    long countByExample(MeetingAnnexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_annex
     *
     * @mbg.generated Sun Mar 15 12:53:12 CST 2020
     */
    int deleteByExample(MeetingAnnexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_annex
     *
     * @mbg.generated Sun Mar 15 12:53:12 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_annex
     *
     * @mbg.generated Sun Mar 15 12:53:12 CST 2020
     */
    int insert(MeetingAnnex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_annex
     *
     * @mbg.generated Sun Mar 15 12:53:12 CST 2020
     */
    int insertSelective(MeetingAnnex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_annex
     *
     * @mbg.generated Sun Mar 15 12:53:12 CST 2020
     */
    List<MeetingAnnex> selectByExample(MeetingAnnexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_annex
     *
     * @mbg.generated Sun Mar 15 12:53:12 CST 2020
     */
    MeetingAnnex selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_annex
     *
     * @mbg.generated Sun Mar 15 12:53:12 CST 2020
     */
    int updateByExampleSelective(@Param("record") MeetingAnnex record, @Param("example") MeetingAnnexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_annex
     *
     * @mbg.generated Sun Mar 15 12:53:12 CST 2020
     */
    int updateByExample(@Param("record") MeetingAnnex record, @Param("example") MeetingAnnexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_annex
     *
     * @mbg.generated Sun Mar 15 12:53:12 CST 2020
     */
    int updateByPrimaryKeySelective(MeetingAnnex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_annex
     *
     * @mbg.generated Sun Mar 15 12:53:12 CST 2020
     */
    int updateByPrimaryKey(MeetingAnnex record);
}