package cn.yiueil.meeting.mapper;

import cn.yiueil.meeting.entity.MeetingRemind;
import cn.yiueil.meeting.entity.MeetingRemindExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MeetingRemindMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_remind
     *
     * @mbg.generated Wed Mar 25 13:40:37 CST 2020
     */
    long countByExample(MeetingRemindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_remind
     *
     * @mbg.generated Wed Mar 25 13:40:37 CST 2020
     */
    int deleteByExample(MeetingRemindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_remind
     *
     * @mbg.generated Wed Mar 25 13:40:37 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_remind
     *
     * @mbg.generated Wed Mar 25 13:40:37 CST 2020
     */
    int insert(MeetingRemind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_remind
     *
     * @mbg.generated Wed Mar 25 13:40:37 CST 2020
     */
    int insertSelective(MeetingRemind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_remind
     *
     * @mbg.generated Wed Mar 25 13:40:37 CST 2020
     */
    List<MeetingRemind> selectByExample(MeetingRemindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_remind
     *
     * @mbg.generated Wed Mar 25 13:40:37 CST 2020
     */
    MeetingRemind selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_remind
     *
     * @mbg.generated Wed Mar 25 13:40:37 CST 2020
     */
    int updateByExampleSelective(@Param("record") MeetingRemind record, @Param("example") MeetingRemindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_remind
     *
     * @mbg.generated Wed Mar 25 13:40:37 CST 2020
     */
    int updateByExample(@Param("record") MeetingRemind record, @Param("example") MeetingRemindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_remind
     *
     * @mbg.generated Wed Mar 25 13:40:37 CST 2020
     */
    int updateByPrimaryKeySelective(MeetingRemind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_meeting_remind
     *
     * @mbg.generated Wed Mar 25 13:40:37 CST 2020
     */
    int updateByPrimaryKey(MeetingRemind record);
}