package cn.yiueil.meeting.mapper;

import cn.yiueil.meeting.entity.Profession;
import cn.yiueil.meeting.entity.ProfessionExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProfessionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profession
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    long countByExample(ProfessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profession
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    int deleteByExample(ProfessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profession
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profession
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    int insert(Profession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profession
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    int insertSelective(Profession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profession
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    List<Profession> selectByExample(ProfessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profession
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    Profession selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profession
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    int updateByExampleSelective(@Param("record") Profession record, @Param("example") ProfessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profession
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    int updateByExample(@Param("record") Profession record, @Param("example") ProfessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profession
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    int updateByPrimaryKeySelective(Profession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profession
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    int updateByPrimaryKey(Profession record);
}