package cn.yiueil.meeting.entity;

public class Login {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login.id
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login.name
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login.mail
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login.phone
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login.passwd
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    private String passwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login.islogin
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    private Boolean islogin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login.id
     *
     * @return the value of t_login.id
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login.id
     *
     * @param id the value for t_login.id
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login.name
     *
     * @return the value of t_login.name
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login.name
     *
     * @param name the value for t_login.name
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login.mail
     *
     * @return the value of t_login.mail
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login.mail
     *
     * @param mail the value for t_login.mail
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login.phone
     *
     * @return the value of t_login.phone
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login.phone
     *
     * @param phone the value for t_login.phone
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login.passwd
     *
     * @return the value of t_login.passwd
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login.passwd
     *
     * @param passwd the value for t_login.passwd
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login.islogin
     *
     * @return the value of t_login.islogin
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public Boolean getIslogin() {
        return islogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login.islogin
     *
     * @param islogin the value for t_login.islogin
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public void setIslogin(Boolean islogin) {
        this.islogin = islogin;
    }
}