package cn.yiueil.meeting.entity;

public class MeetingUser extends MeetingUserKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_meeting_user.mrole
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    private String mrole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_meeting_user.status
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_meeting_user.mrole
     *
     * @return the value of t_meeting_user.mrole
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public String getMrole() {
        return mrole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_meeting_user.mrole
     *
     * @param mrole the value for t_meeting_user.mrole
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public void setMrole(String mrole) {
        this.mrole = mrole == null ? null : mrole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_meeting_user.status
     *
     * @return the value of t_meeting_user.status
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_meeting_user.status
     *
     * @param status the value for t_meeting_user.status
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}