package cn.yiueil.meeting.entity;

import java.util.Date;

public class Meeting {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_meeting.id
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_meeting.title
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_meeting.release_time
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    private Date releaseTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_meeting.start_time
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_meeting.end_time
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_meeting.place
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    private String place;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_meeting.audio
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    private String audio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_meeting.remarks
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_meeting.status
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_meeting.text
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    private String text;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_meeting.id
     *
     * @return the value of t_meeting.id
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_meeting.id
     *
     * @param id the value for t_meeting.id
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_meeting.title
     *
     * @return the value of t_meeting.title
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_meeting.title
     *
     * @param title the value for t_meeting.title
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_meeting.release_time
     *
     * @return the value of t_meeting.release_time
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public Date getReleaseTime() {
        return releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_meeting.release_time
     *
     * @param releaseTime the value for t_meeting.release_time
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public void setReleaseTime(Date releaseTime) {
        this.releaseTime = releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_meeting.start_time
     *
     * @return the value of t_meeting.start_time
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_meeting.start_time
     *
     * @param startTime the value for t_meeting.start_time
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_meeting.end_time
     *
     * @return the value of t_meeting.end_time
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_meeting.end_time
     *
     * @param endTime the value for t_meeting.end_time
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_meeting.place
     *
     * @return the value of t_meeting.place
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_meeting.place
     *
     * @param place the value for t_meeting.place
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_meeting.audio
     *
     * @return the value of t_meeting.audio
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public String getAudio() {
        return audio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_meeting.audio
     *
     * @param audio the value for t_meeting.audio
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public void setAudio(String audio) {
        this.audio = audio == null ? null : audio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_meeting.remarks
     *
     * @return the value of t_meeting.remarks
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_meeting.remarks
     *
     * @param remarks the value for t_meeting.remarks
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_meeting.status
     *
     * @return the value of t_meeting.status
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_meeting.status
     *
     * @param status the value for t_meeting.status
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_meeting.text
     *
     * @return the value of t_meeting.text
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_meeting.text
     *
     * @param text the value for t_meeting.text
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }
}