package cn.yiueil.meeting.entity;

public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.id
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.msg
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    private String msg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.uid
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.isread
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    private Boolean isread;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.id
     *
     * @return the value of t_message.id
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.id
     *
     * @param id the value for t_message.id
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.msg
     *
     * @return the value of t_message.msg
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.msg
     *
     * @param msg the value for t_message.msg
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.uid
     *
     * @return the value of t_message.uid
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.uid
     *
     * @param uid the value for t_message.uid
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.isread
     *
     * @return the value of t_message.isread
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public Boolean getIsread() {
        return isread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.isread
     *
     * @param isread the value for t_message.isread
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public void setIsread(Boolean isread) {
        this.isread = isread;
    }
}