package cn.yiueil.meeting.entity;

public class Profession {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profession.id
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profession.name
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profession.id
     *
     * @return the value of t_profession.id
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profession.id
     *
     * @param id the value for t_profession.id
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profession.name
     *
     * @return the value of t_profession.name
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profession.name
     *
     * @param name the value for t_profession.name
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}