package cn.yiueil.meeting.entity;

public class Remind {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remind.id
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remind.of
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    private Byte of;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remind.type
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remind.param
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    private Integer param;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remind.enable
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    private Boolean enable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remind.uid
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    private Long uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remind.id
     *
     * @return the value of t_remind.id
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remind.id
     *
     * @param id the value for t_remind.id
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remind.of
     *
     * @return the value of t_remind.of
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public Byte getOf() {
        return of;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remind.of
     *
     * @param of the value for t_remind.of
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public void setOf(Byte of) {
        this.of = of;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remind.type
     *
     * @return the value of t_remind.type
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remind.type
     *
     * @param type the value for t_remind.type
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remind.param
     *
     * @return the value of t_remind.param
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public Integer getParam() {
        return param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remind.param
     *
     * @param param the value for t_remind.param
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public void setParam(Integer param) {
        this.param = param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remind.enable
     *
     * @return the value of t_remind.enable
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remind.enable
     *
     * @param enable the value for t_remind.enable
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remind.uid
     *
     * @return the value of t_remind.uid
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remind.uid
     *
     * @param uid the value for t_remind.uid
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }
}