package cn.yiueil.meeting.entity;

public class Remind {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remind.id
     *
     * @mbg.generated Fri Mar 20 21:05:23 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remind.rof
     *
     * @mbg.generated Fri Mar 20 21:05:23 CST 2020
     */
    private Byte rof;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remind.rtype
     *
     * @mbg.generated Fri Mar 20 21:05:23 CST 2020
     */
    private Byte rtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remind.rparam
     *
     * @mbg.generated Fri Mar 20 21:05:23 CST 2020
     */
    private Integer rparam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remind.renable
     *
     * @mbg.generated Fri Mar 20 21:05:23 CST 2020
     */
    private Boolean renable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remind.uid
     *
     * @mbg.generated Fri Mar 20 21:05:23 CST 2020
     */
    private Long uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remind.id
     *
     * @return the value of t_remind.id
     *
     * @mbg.generated Fri Mar 20 21:05:23 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remind.id
     *
     * @param id the value for t_remind.id
     *
     * @mbg.generated Fri Mar 20 21:05:23 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remind.rof
     *
     * @return the value of t_remind.rof
     *
     * @mbg.generated Fri Mar 20 21:05:23 CST 2020
     */
    public Byte getRof() {
        return rof;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remind.rof
     *
     * @param rof the value for t_remind.rof
     *
     * @mbg.generated Fri Mar 20 21:05:23 CST 2020
     */
    public void setRof(Byte rof) {
        this.rof = rof;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remind.rtype
     *
     * @return the value of t_remind.rtype
     *
     * @mbg.generated Fri Mar 20 21:05:23 CST 2020
     */
    public Byte getRtype() {
        return rtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remind.rtype
     *
     * @param rtype the value for t_remind.rtype
     *
     * @mbg.generated Fri Mar 20 21:05:23 CST 2020
     */
    public void setRtype(Byte rtype) {
        this.rtype = rtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remind.rparam
     *
     * @return the value of t_remind.rparam
     *
     * @mbg.generated Fri Mar 20 21:05:23 CST 2020
     */
    public Integer getRparam() {
        return rparam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remind.rparam
     *
     * @param rparam the value for t_remind.rparam
     *
     * @mbg.generated Fri Mar 20 21:05:23 CST 2020
     */
    public void setRparam(Integer rparam) {
        this.rparam = rparam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remind.renable
     *
     * @return the value of t_remind.renable
     *
     * @mbg.generated Fri Mar 20 21:05:23 CST 2020
     */
    public Boolean getRenable() {
        return renable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remind.renable
     *
     * @param renable the value for t_remind.renable
     *
     * @mbg.generated Fri Mar 20 21:05:23 CST 2020
     */
    public void setRenable(Boolean renable) {
        this.renable = renable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remind.uid
     *
     * @return the value of t_remind.uid
     *
     * @mbg.generated Fri Mar 20 21:05:23 CST 2020
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remind.uid
     *
     * @param uid the value for t_remind.uid
     *
     * @mbg.generated Fri Mar 20 21:05:23 CST 2020
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }
}