package cn.yiueil.meeting.entity;

public class UserGroupKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_group.gid
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    private Long gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_group.uid
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    private Long uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_group.gid
     *
     * @return the value of t_user_group.gid
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public Long getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_group.gid
     *
     * @param gid the value for t_user_group.gid
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public void setGid(Long gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_group.uid
     *
     * @return the value of t_user_group.uid
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_group.uid
     *
     * @param uid the value for t_user_group.uid
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }
}