package cn.yiueil.meeting.entity;

public class UserGroup extends UserGroupKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_group.urole
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    private String urole;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_group.urole
     *
     * @return the value of t_user_group.urole
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public String getUrole() {
        return urole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_group.urole
     *
     * @param urole the value for t_user_group.urole
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public void setUrole(String urole) {
        this.urole = urole == null ? null : urole.trim();
    }
}