package cn.yiueil.meeting.entity;

public class UserRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.id
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.uid
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.rid
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    private Long rid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role.id
     *
     * @return the value of t_user_role.id
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role.id
     *
     * @param id the value for t_user_role.id
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role.uid
     *
     * @return the value of t_user_role.uid
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role.uid
     *
     * @param uid the value for t_user_role.uid
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role.rid
     *
     * @return the value of t_user_role.rid
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public Long getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role.rid
     *
     * @param rid the value for t_user_role.rid
     *
     * @mbg.generated Sat Mar 14 22:42:03 CST 2020
     */
    public void setRid(Long rid) {
        this.rid = rid;
    }
}